// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import Helpers__Components__ArbolNavegacionController from "./helpers/components/arbol_navegacion_controller"
application.register("helpers--components--arbol-navegacion", Helpers__Components__ArbolNavegacionController)

import Helpers__Components__ThemeToggleController from "./helpers/components/theme_toggle_controller"
application.register("helpers--components--theme-toggle", Helpers__Components__ThemeToggleController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import SelectDependencyController from "./select_dependency_controller"
application.register("select-dependency", SelectDependencyController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)
